---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86130.
--- DateTime: 2023/2/1 18:25
---

local voucherId=ARGV[1]
local userId=ARGV[2]
--local orderId=ARGV[3]

--lua 语言用 .. 进行字符串拼接
local voucherKey="seckill:stock:" .. voucherId
local orderKey="seckill:order:" ..voucherId

--判断优惠券是否充足
if (tonumber(redis.call('get', voucherKey)) <= 0) then
   return 1
end

--如果 member 是 key 的元素，则返回 1，如果 member 不是 key 的元素，或 key 不存在，返回 0

if (tonumber(redis.call('sismember', orderKey , userId)) == 1) then
    return 2
end

redis.call('decr', voucherKey)
redis.call('sadd' , orderKey , userId)

return 0

