---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86130.
--- DateTime: 2023/1/31 23:01
---


local voucherId = KEYS[1]
if (tonumber(redis.call('get', voucherId))<=0) then
    return 1
end
redis.call('decr', voucherId)
return 0