---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86130.
--- DateTime: 2023/1/17 22:36
---

if(redis.call('get',KEYS[1]) == ARGV[1] ) then
    return redis.call('del',KEYS[1])
end
return 0